# -*- coding: utf-8 -*-
"""LR_1_task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkkvWnBOhzlCsti05-vpyRWdAbaceQn7

# ЛР 1 — Завдання 2.1: Попередня обробка даних

**Бінаризація, виключення середнього, масштабування, нормалізація** (Google Colab варіант)

### Мета
Показати ключові прийоми попередньої обробки та інтерпретувати результат.
"""

# Commented out IPython magic to ensure Python compatibility.

import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt
# %matplotlib inline

# Вихідні дані
input_data = np.array([
    [5.1, -2.9,  3.3],
    [-1.2, 7.8, -6.1],
    [3.9,  0.4,  2.1],
    [7.3, -9.9, -4.5]
], dtype=float)

print("Дані:\n", input_data)

"""#### 1) Бінаризація (поріг 2.1)"""

binarizer = preprocessing.Binarizer(threshold=2.1)
data_binarized = binarizer.transform(input_data)
print("Binarized data:\n", data_binarized)

"""#### 2) Виключення середнього (z-score)"""

print("BEFORE: mean:", input_data.mean(axis=0), " std:", input_data.std(axis=0))
data_scaled = preprocessing.scale(input_data)
print("AFTER : mean:", data_scaled.mean(axis=0), " std:", data_scaled.std(axis=0))

"""#### 3) Масштабування Min–Max до [0,1]"""

mm = preprocessing.MinMaxScaler((0,1))
data_minmax = mm.fit_transform(input_data)
print("Min–max scaled:\n", data_minmax)

"""#### 4) Нормалізація L1 та L2"""

l1 = preprocessing.normalize(input_data, norm='l1')
l2 = preprocessing.normalize(input_data, norm='l2')
print("L1:\n", l1)
print("\nL2:\n", l2)

print("\nВисновок: L1 стійкіша до викидів (нормує суму модулів до 1), L2 — суму квадратів до 1.")