# -*- coding: utf-8 -*-
"""LR_1_task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qjh6067Kd-D8Xg5OBkTcN3yyKwcmeme8
"""

import numpy as np
from sklearn import preprocessing

input_data = np.array([[5.1, -2.9, 3.3],
                       [-1.2, 7.8, -6.1],
                       [3.9, 0.4, 2.1],
                       [7.3, -9.9, -4.5]], dtype=float)
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print(data_binarized)
print(input_data.mean(axis=0))
print(input_data.std(axis=0))
data_scaled = preprocessing.scale(input_data)
print(data_scaled.mean(axis=0))
print(data_scaled.std(axis=0))
mm = preprocessing.MinMaxScaler((0,1)).fit_transform(input_data)
print(mm)
l1 = preprocessing.normalize(input_data, norm='l1')
l2 = preprocessing.normalize(input_data, norm='l2')
print(l1)
print(l2)

from sklearn import preprocessing as prep
input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow', 'white']
encoder = prep.LabelEncoder().fit(input_labels)
for i, item in enumerate(encoder.classes_):
    print(item, i)
test_labels = ['green', 'red', 'black']
print(encoder.transform(test_labels))
print(list(encoder.inverse_transform([3,0,1])))