# -*- coding: utf-8 -*-
"""LR_1_task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188WM8L_SUn5ADifvHR7SCVKjj1kMmhZ3

# ЛР 1 — Завдання 2.3: Логістична регресія (класифікація + візуалізація)
"""

# Commented out IPython magic to ensure Python compatibility.

import numpy as np, matplotlib.pyplot as plt
from sklearn import linear_model
# %matplotlib inline

# Дані з методички
X = np.array([[3.1,7.2],[4,6.7],[2.9,8],[5.1,4.5],[6,5],[5.6,5],
              [3.3,0.4],[3.9,0.9],[2.8,1],
              [0.5,3.4],[1,4],[0.6,4.9]], dtype=float)
y = np.array([0,0,0, 1,1,1, 2,2,2, 3,3,3])

clf = linear_model.LogisticRegression(solver='liblinear', C=1.0).fit(X,y)

def visualize_classifier(classifier, X, y, h=0.02):
    x_min, x_max = X[:,0].min()-0.5, X[:,0].max()+0.5
    y_min, y_max = X[:,1].min()-0.5, X[:,1].max()+0.5
    xx, yy = np.meshgrid(np.arange(x_min,x_max,h), np.arange(y_min,y_max,h))
    Z = classifier.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)
    plt.figure()
    plt.contourf(xx, yy, Z, alpha=0.3)
    plt.scatter(X[:,0], X[:,1], c=y, edgecolor='k')
    plt.xlabel("X1"); plt.ylabel("X2"); plt.title("Межі рішень логістичної регресії")
    plt.show()

visualize_classifier(clf, X, y)

"""Висновок:
Логістична регресія правильно розділила точки на чотири класи, побудувавши помітні межі рішень. Метод добре працює для лінійно роздільних даних і показує, як змінюються області належності класів на площині.
"""