# -*- coding: utf-8 -*-
"""LR_1_task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1329LCRw42AdxrQNiK3Bgamg5hLPgT7-s
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

def visualize_classifier(classifier, X, y, title=''):
    x_min, x_max = X[:,0].min()-1.0, X[:,0].max()+1.0
    y_min, y_max = X[:,1].min()-1.0, X[:,1].max()+1.0
    h = 0.02
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    Z = classifier.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)
    plt.contourf(xx, yy, Z, alpha=0.25)
    for cls in np.unique(y):
        pts = X[y==cls]
        plt.scatter(pts[:,0], pts[:,1], edgecolor='k')
    plt.title(title)
    plt.tight_layout()
    plt.show()

X = np.array([[3.1, 7.2], [4, 6.7], [2.9, 8], [5.1, 4.5],
              [6, 5], [5.6, 5], [3.3, 0.4],
              [3.9, 0.9], [2.8, 1],
              [0.5, 3.4], [1, 4], [0.6, 4.9]])
y = np.array([0,0,0,1,1,1,2,2,2,3,3,3])
clf = linear_model.LogisticRegression(solver='liblinear', C=1)
clf.fit(X, y)
visualize_classifier(clf, X, y)