# -*- coding: utf-8 -*-
"""LR_1_task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WT4fgLCJOtL1YkXVHdh60yuhA9Xy7tnr

# ЛР 1 — Завдання 2.2: Попередня обробка **нових даних** за варіантом
"""

import numpy as np
from sklearn import preprocessing

values = [-3.3, -1.6, 6.1, 2.4, -1.2, 4.3, -3.2, 5.5, -6.1, -4.4, 1.4, -1.2]
threshold = 2.1

input_data = np.array(values, dtype=float).reshape(-1,3)
print("Дані (Nx3):\n", input_data)

"""#### 1) Бінаризація"""

data_bin = preprocessing.Binarizer(threshold=threshold).transform(input_data)
print("Binarized:\n", data_bin)

"""#### 2) Виключення середнього"""

print("BEFORE mean:", input_data.mean(axis=0), " std:", input_data.std(axis=0))
data_scaled = preprocessing.scale(input_data)
print("AFTER  mean:", data_scaled.mean(axis=0), " std:", data_scaled.std(axis=0))

"""#### 3) Масштабування Min–Max"""

mm = preprocessing.MinMaxScaler((0,1))
data_mm = mm.fit_transform(input_data)
print("Min–Max:\n", data_mm)

"""#### 4) Нормалізація L1/L2"""

l1 = preprocessing.normalize(input_data, 'l1')
l2 = preprocessing.normalize(input_data, 'l2')
print("L1:\n", l1)
print("\nL2:\n", l2)

"""Висновок:
Дані успішно оброблено. Після бінаризації, масштабування й нормалізації всі значення приведено до зручного діапазону та готові для подальшого аналізу.
"""