# -*- coding: utf-8 -*-
"""LR_1_task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZ1O0TwuwAwWGVKk2CO3Oy2ka65Bg7s3
"""

import numpy as np
from sklearn import preprocessing

values = [-3.3, -1.6, 6.1, 2.4, -1.2, 4.3, -3.2, 5.5, -6.1, -4.4, 1.4, -1.2, 2.1]
threshold = float(values[-1])
vals = np.array(values[:-1], dtype=float)
assert vals.size % 3 == 0
input_data_new = vals.reshape((-1, 3))
binarized = preprocessing.Binarizer(threshold=threshold).transform(input_data_new)
print(binarized)
scaled = preprocessing.scale(input_data_new)
print(scaled.mean(axis=0))
print(scaled.std(axis=0))
minmax = preprocessing.MinMaxScaler((0,1)).fit_transform(input_data_new)
print(minmax)
norm_l1 = preprocessing.normalize(input_data_new, norm='l1')
norm_l2 = preprocessing.normalize(input_data_new, norm='l2')
print(norm_l1)
print(norm_l2)